spring.application.name=ConfigServer

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Jyothiraditya-kesanakurthi/Greythr_MicroService-Database-Propertites/blob/main/application.properties